//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidBloatwareDisabler.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AndroidBloatwareDisabler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All packages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AllPackages {
            get {
                return ResourceManager.GetString("AllPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checked packages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckedPackages {
            get {
                return ResourceManager.GetString("CheckedPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} device(s) found. {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DevicesFound {
            get {
                return ResourceManager.GetString("DevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disabled packages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisabledPackages {
            get {
                return ResourceManager.GetString("DisabledPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enabled packages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnabledPackages {
            get {
                return ResourceManager.GetString("EnabledPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListItem_Device {
            get {
                return ResourceManager.GetString("ListItem_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListItem_Model {
            get {
                return ResourceManager.GetString("ListItem_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListItem_Name {
            get {
                return ResourceManager.GetString("ListItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Package name and state に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PackageNameAndState {
            get {
                return ResourceManager.GetString("PackageNameAndState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Package name only に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PackageNameOnly {
            get {
                return ResourceManager.GetString("PackageNameOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} package(s) have been dumped. {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PackagesDumped {
            get {
                return ResourceManager.GetString("PackagesDumped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} package(s) found. {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PackagesFound {
            get {
                return ResourceManager.GetString("PackagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} package(s) have been switched. {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PackagesSwitched {
            get {
                return ResourceManager.GetString("PackagesSwitched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System packages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SystemPackages {
            get {
                return ResourceManager.GetString("SystemPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The check status of {0} package(s) has been changed. {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TheCheckStatusOfPackagesHasBeenChanged {
            get {
                return ResourceManager.GetString("TheCheckStatusOfPackagesHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no package that can be applied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThereIsNoPackageThatCanBeChanged {
            get {
                return ResourceManager.GetString("ThereIsNoPackageThatCanBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no package that can be dumped. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThereIsNoPackageThatCanBeDumped {
            get {
                return ResourceManager.GetString("ThereIsNoPackageThatCanBeDumped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thirdparty packages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThirdpartyPackages {
            get {
                return ResourceManager.GetString("ThirdpartyPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unchecked packages に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UncheckedPackages {
            get {
                return ResourceManager.GetString("UncheckedPackages", resourceCulture);
            }
        }
    }
}
